name: streamio_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_secure_storage_windows: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  material_color_utilities: 0.11.1



dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
